export type TMessages = {
  [key: string]: string
}

export const en: TMessages = {
  aria_label_episode_table_list: 'Episode Table List',
  aria_label_go_to: 'Go to',
  aria_label_episode_date: 'Episode date',
  aria_label_episode_duration: 'Episode duration',
  back_to_home: '← Back to Home',
  metadata_title: 'Podcasts App - Generated by create next app - by René Rubio',
  metadata_description:
    'Podcasts App - Generated by create next app - by René Rubio',
  podcaster: 'Podcaster',
  error_load_top_100: 'Failed to load Top 100',
  home_title: 'Top 100 Podcasts',
  loading: 'Loading…',
  error_loading_data: 'Error loading data.',
  error_use_navigation_context:
    'useNavigationContext must be used within LoadingProvider',
  description: 'Description',
  author: 'Author',
  filter_podcasts_placeholder: 'Filter podcasts...',
  home: 'Home',
  episode: 'Episode',
  podcast: 'Podcast',
  page: 'Page',
  title_song: 'Title song',
  author_song: 'Author song',
  logo_song: 'Logo song',
  error_network:
    "We couldn't connect to the server. Please try again when you have a network connection.",
  offline: 'You are offline',
  podcast_detail: 'Podcast Details',
  podcast_not_found: 'Podcast not found',
  not_found: 'not found.',
  episodes: 'Episodes',
  by: 'by',
  title: 'Title',
  date: 'Date',
  duration: 'Duration',
  unknown: 'Unknown',
  loading_top_podcasts: 'Loading top 100 podcasts...',
  loading_podcast_details: 'Loading podcast: ',
  loading_episode_details: 'Loading episode: ',
  go_to: 'Go to',
  episode_detail: 'Episode Detail',
  no_image_available: 'No image available',
  error_loading_podcasts: 'Error loading podcasts.',
  no_podcasts_found: 'No podcasts found.'
}
