type Messages = {
  [key: string]: string
}
export const en: Messages = {
  back_to_home: '← Back to Home',
  metadata_title: 'Podcasts App - Generated by create next app - by René Rubio',
  metadata_description:
    'Podcasts App - Generated by create next app - by René Rubio',
  podcaster: 'Podcaster',
  error_load_top_100: 'Failed to load Top 100',
  home_title: 'Top 100 Podcasts',
  loading: 'Loading…',
  error_loading_data: 'Error loading data.',
  error_use_navigation_context:
    'useNavigationContext must be used within NavigationProvider',
  podcast_description: 'Description',
  author: 'Author',
  filter_podcasts_placeholder: 'Filter podcasts...',
  home: 'Home',
  episode: 'Episode',
  podcast: 'Podcast',
  page: 'Page',
  title_song: 'Title song',
  author_song: 'Author song',
  logo_song: 'Logo song'
}
