import AppHeader from '@/components/AppHeader'
import NavIndicator from '@/components/NavIndicator'
import { NavigationProvider } from '@/context/NavigationContext'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Podcasts App - Generated by create next app - by René Rubio',
  description: 'Podcasts App - Generated by create next app - by René Rubio'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>
        <NavigationProvider>
          <AppHeader />
          <NavIndicator />
          <main>{children}</main>
        </NavigationProvider>
      </body>
    </html>
  )
}
