/* eslint-disable consistent-return */
import { TIMEOUT_TOAST_OUT_MS } from '@/utils/constants'

/**
 * Executes the provided `stop` function after a specified timeout.
 *
 * @param params - The parameters for the function.
 * @param params.stop - The function to be executed after the timeout.
 * @param params.timeout - Optional. The delay in milliseconds before executing `stop`. Defaults to `TIMEOUT_TOAST_OUT_MS`.
 */
export function stopWithTimeout({
  stop,
  timeout = TIMEOUT_TOAST_OUT_MS
}: {
  stop: () => void
  timeout?: number
}) {
  setTimeout(() => {
    stop()
  }, timeout)
}

const DAY_MS = 24 * 60 * 60 * 1000

/**
 * Stores a value in localStorage with an associated time-to-live (TTL).
 *
 * @param key - The key under which the value will be stored in localStorage.
 * @param value - The value to store. Can be any serializable data.
 * @param ttlMs - The time-to-live in milliseconds. Defaults to `DAY_MS` if not provided.
 *
 * The stored payload is an object with the following properties:
 * - `value`: The actual value being stored.
 * - `ts`: The timestamp (in milliseconds since the Unix epoch) when the value was stored, generated by `Date.now()`.
 * - `ttl`: The time-to-live in milliseconds, indicating how long the value should be considered valid.
 *
 * If called in a non-browser environment (where `window` is undefined), the function returns `null` and does not attempt to access localStorage.
 */
export function lsSetWithTTL(key: string, value: any, ttlMs = DAY_MS) {
  const payload = { value, ts: Date.now(), ttl: ttlMs }
  if (typeof window === 'undefined') return null
  localStorage.setItem(key, JSON.stringify(payload))
}

/**
 * Retrieves a value from localStorage by key, supporting an optional time-to-live (TTL) mechanism.
 * If the stored item has expired based on its timestamp (`ts`) and TTL, it is removed and `null` is returned.
 * If the item is not found or cannot be parsed, `null` is returned.
 *
 * The stored value in localStorage is expected to be a JSON string with the following properties:
 * - `value`: The actual value to be retrieved.
 * - `ts`: The timestamp (in milliseconds since epoch) when the value was stored.
 * - `ttl`: (Optional) The time-to-live in milliseconds. If not provided, defaults to `DAY_MS`.
 *
 * @param key - The localStorage key to retrieve.
 * @returns The stored value if it exists and has not expired, otherwise `null`.
 */
export function lsGetWithTTL(key: string) {
  if (typeof window === 'undefined') return null
  const raw = localStorage.getItem(key)
  if (!raw) return null

  try {
    const { value, ts, ttl = DAY_MS } = JSON.parse(raw)
    if (Date.now() - ts > ttl) {
      localStorage.removeItem(key)
      return null
    }
    return value
  } catch {
    localStorage.removeItem(key)
    return null
  }
}
